/**
 * In-Page Recorder Script for QA Recorder
 * Injected into the embedded browser view to capture user interactions,
 * compute robust Playwright selectors with 2-3 fallbacks,
 * and provide an on-page right-click assertion context menu.
 */

import { ipcRenderer } from "electron";

interface SelectorInfo {
  strategy: "data-testid" | "role" | "label" | "placeholder" | "text" | "css" | "xpath";
  value: string;
  playwrightCode: string;
}

interface RecordedStepPayload {
  action: string;
  name: string;
  primarySelector?: SelectorInfo;
  fallbackSelectors?: SelectorInfo[];
  value?: string;
  isPassword?: boolean;
  url?: string;
  timestamp: number;
  targetDescription?: string;
}

// Global recording active flag
let isRecording = false;
let activeContextMenu: HTMLElement | null = null;
let inputDebounceTimer: any = null;
let pendingInputTarget: HTMLInputElement | HTMLTextAreaElement | null = null;

// Listen for recording start/stop from Electron Main
ipcRenderer.on("recorder:set-recording", (_event, recordingState: boolean) => {
  isRecording = recordingState;
  if (!isRecording && activeContextMenu) {
    activeContextMenu.remove();
    activeContextMenu = null;
  }
});

// Helper: generate friendly description of an element
function getElementDescription(el: HTMLElement): string {
  const tag = el.tagName.toLowerCase();
  const text = (el.innerText || el.textContent || "").trim().slice(0, 25);
  const name = el.getAttribute("name") || el.getAttribute("aria-label") || el.getAttribute("placeholder");
  if (text) return `"${text}" ${tag}`;
  if (name) return `"${name}" ${tag}`;
  return tag;
}

// Helper: check if a string looks like an auto-generated random ID or hash
function isAutoGeneratedId(id: string): boolean {
  if (!id) return true;
  // Patterns like :r1:, _1a2b3c, guid, react-generated ids, or purely numeric ids
  if (/^[:_]r[0-9a-zA-Z]+/.test(id)) return true;
  if (/^[0-9]+$/.test(id)) return true;
  if (/[a-f0-9]{8}-[a-f0-9]{4}/i.test(id)) return true;
  if (id.length > 25 && /[0-9]/.test(id)) return true;
  return false;
}

// Determine ARIA role for Playwright getByRole
function getAriaRole(el: HTMLElement): string | null {
  const explicitRole = el.getAttribute("role");
  if (explicitRole) return explicitRole.toLowerCase();

  const tag = el.tagName.toLowerCase();
  if (tag === "button") return "button";
  if (tag === "a" && el.hasAttribute("href")) return "link";
  if (tag === "input") {
    const type = (el.getAttribute("type") || "text").toLowerCase();
    if (type === "button" || type === "submit" || type === "reset") return "button";
    if (type === "checkbox") return "checkbox";
    if (type === "radio") return "radio";
    return "textbox";
  }
  if (tag === "textarea") return "textbox";
  if (tag === "select") return "combobox";
  if (/^h[1-6]$/.test(tag)) return "heading";
  if (tag === "img") return "img";
  return null;
}

// Extract accessible name for getByRole
function getAccessibleName(el: HTMLElement): string {
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel?.trim()) return ariaLabel.trim();

  const title = el.getAttribute("title");
  if (title?.trim()) return title.trim();

  // For buttons/links/headers: visible text
  const text = (el.innerText || el.textContent || "").trim();
  if (text) return text.split("\n")[0].trim().slice(0, 40);

  const placeholder = el.getAttribute("placeholder");
  if (placeholder?.trim()) return placeholder.trim();

  return "";
}

// Check associated label
function getAssociatedLabel(el: HTMLElement): string | null {
  if (el.id) {
    const labelEl = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
    if (labelEl && labelEl.textContent?.trim()) {
      return labelEl.textContent.trim().slice(0, 40);
    }
  }
  const parentLabel = el.closest("label");
  if (parentLabel && parentLabel.textContent?.trim()) {
    return parentLabel.textContent.trim().slice(0, 40);
  }
  return null;
}

/**
 * Generate selectors strictly in priority order:
 * 1. data-testid
 * 2. getByRole(name)
 * 3. getByLabel
 * 4. getByPlaceholder
 * 5. getByText
 * 6. stable CSS
 * 
 * Returns primarySelector and 2-3 fallbackSelectors.
 */
function generateSelectors(el: HTMLElement): {
  primary: SelectorInfo;
  fallbacks: SelectorInfo[];
} {
  const candidates: SelectorInfo[] = [];

  // 1. data-testid (or data-test, data-qa, data-cy)
  const testIdAttrs = ["data-testid", "data-test", "data-qa", "data-cy"];
  for (const attr of testIdAttrs) {
    const val = el.getAttribute(attr);
    if (val) {
      candidates.push({
        strategy: "data-testid",
        value: val,
        playwrightCode: `page.getByTestId(${JSON.stringify(val)})`,
      });
      break;
    }
  }

  // 2. getByRole(name)
  const role = getAriaRole(el);
  const name = getAccessibleName(el);
  if (role) {
    if (name) {
      candidates.push({
        strategy: "role",
        value: `${role}[name="${name}"]`,
        playwrightCode: `page.getByRole(${JSON.stringify(role)}, { name: ${JSON.stringify(name)} })`,
      });
    } else {
      candidates.push({
        strategy: "role",
        value: role,
        playwrightCode: `page.getByRole(${JSON.stringify(role)})`,
      });
    }
  }

  // 3. getByLabel
  const labelText = getAssociatedLabel(el);
  if (labelText) {
    candidates.push({
      strategy: "label",
      value: labelText,
      playwrightCode: `page.getByLabel(${JSON.stringify(labelText)})`,
    });
  }

  // 4. getByPlaceholder
  const placeholder = el.getAttribute("placeholder");
  if (placeholder?.trim()) {
    candidates.push({
      strategy: "placeholder",
      value: placeholder.trim(),
      playwrightCode: `page.getByPlaceholder(${JSON.stringify(placeholder.trim())})`,
    });
  }

  // 5. getByText (for buttons, links, spans, headings)
  const text = (el.innerText || el.textContent || "").trim();
  if (text && text.length < 50 && !["input", "textarea"].includes(el.tagName.toLowerCase())) {
    const cleanText = text.split("\n")[0].trim();
    candidates.push({
      strategy: "text",
      value: cleanText,
      playwrightCode: `page.getByText(${JSON.stringify(cleanText)}, { exact: true })`,
    });
  }

  // 6. Stable CSS: ID, unique name, unique class combinations
  if (el.id && !isAutoGeneratedId(el.id)) {
    const idSelector = `#${CSS.escape(el.id)}`;
    candidates.push({
      strategy: "css",
      value: idSelector,
      playwrightCode: `page.locator(${JSON.stringify(idSelector)})`,
    });
  }

  const nameAttr = el.getAttribute("name");
  if (nameAttr) {
    const nameCss = `${el.tagName.toLowerCase()}[name="${CSS.escape(nameAttr)}"]`;
    candidates.push({
      strategy: "css",
      value: nameCss,
      playwrightCode: `page.locator(${JSON.stringify(nameCss)})`,
    });
  }

  // Class-based fallback if classes look semantic
  if (el.className && typeof el.className === "string") {
    const semanticClasses = el.className
      .split(/\s+/)
      .filter((c) => c && !c.includes(":") && !c.startsWith("_") && c.length > 2 && !/^[0-9]+$/.test(c))
      .slice(0, 2);
    if (semanticClasses.length > 0) {
      const classCss = `${el.tagName.toLowerCase()}.${semanticClasses.join(".")}`;
      candidates.push({
        strategy: "css",
        value: classCss,
        playwrightCode: `page.locator(${JSON.stringify(classCss)})`,
      });
    }
  }

  // Ultimate fallback: simple tag name or XPath
  if (candidates.length === 0) {
    candidates.push({
      strategy: "css",
      value: el.tagName.toLowerCase(),
      playwrightCode: `page.locator(${JSON.stringify(el.tagName.toLowerCase())})`,
    });
  }

  const primary = candidates[0];
  const fallbacks = candidates.slice(1, 4);

  return { primary, fallbacks };
}

// Send captured step to Electron Main
function emitStep(step: RecordedStepPayload) {
  if (!isRecording) return;
  ipcRenderer.send("recorder:step-captured", step);
}

// -------------------------------------------------------------
// EVENT LISTENERS: Capture clicks, dblclicks, inputs, selections
// -------------------------------------------------------------

// Flush pending debounced input
function flushPendingInput() {
  if (pendingInputTarget) {
    const el = pendingInputTarget;
    const isPassword = (el.getAttribute("type") || "").toLowerCase() === "password";
    const { primary, fallbacks } = generateSelectors(el);
    const desc = getElementDescription(el);

    emitStep({
      action: "input",
      name: `Type into ${desc}`,
      primarySelector: primary,
      fallbackSelectors: fallbacks,
      value: el.value,
      isPassword,
      timestamp: Date.now(),
      targetDescription: desc,
    });
    pendingInputTarget = null;
  }
}

// Click & Double Click
window.addEventListener(
  "click",
  (e: MouseEvent) => {
    if (!isRecording) return;
    // Don't record clicks inside our custom assertion context menu
    if (activeContextMenu && activeContextMenu.contains(e.target as Node)) return;

    // Flush any pending typing before recording a click
    clearTimeout(inputDebounceTimer);
    flushPendingInput();

    const target = (e.target as HTMLElement)?.closest("a, button, input, select, textarea, [role], [data-testid], li, div, span") as HTMLElement || (e.target as HTMLElement);
    if (!target) return;

    const { primary, fallbacks } = generateSelectors(target);
    const desc = getElementDescription(target);

    emitStep({
      action: "click",
      name: `Click ${desc}`,
      primarySelector: primary,
      fallbackSelectors: fallbacks,
      timestamp: Date.now(),
      targetDescription: desc,
    });
  },
  true
);

window.addEventListener(
  "dblclick",
  (e: MouseEvent) => {
    if (!isRecording) return;
    const target = (e.target as HTMLElement);
    if (!target) return;

    const { primary, fallbacks } = generateSelectors(target);
    const desc = getElementDescription(target);

    emitStep({
      action: "dblclick",
      name: `Double-click ${desc}`,
      primarySelector: primary,
      fallbackSelectors: fallbacks,
      timestamp: Date.now(),
      targetDescription: desc,
    });
  },
  true
);

// Input & Change with Debounce
window.addEventListener(
  "input",
  (e: Event) => {
    if (!isRecording) return;
    const target = e.target as HTMLInputElement | HTMLTextAreaElement;
    if (!target || !("value" in target)) return;

    pendingInputTarget = target;
    clearTimeout(inputDebounceTimer);
    inputDebounceTimer = setTimeout(() => {
      flushPendingInput();
    }, 400); // 400ms typing debounce
  },
  true
);

// Select dropdown change & Checkbox/Radio toggle
window.addEventListener(
  "change",
  (e: Event) => {
    if (!isRecording) return;
    const target = e.target as HTMLElement;
    if (!target) return;

    const tag = target.tagName.toLowerCase();
    const { primary, fallbacks } = generateSelectors(target);
    const desc = getElementDescription(target);

    if (tag === "select") {
      const selectEl = target as HTMLSelectElement;
      const selectedText = selectEl.options[selectEl.selectedIndex]?.text || selectEl.value;
      emitStep({
        action: "select",
        name: `Select "${selectedText}" in ${desc}`,
        primarySelector: primary,
        fallbackSelectors: fallbacks,
        value: selectEl.value,
        timestamp: Date.now(),
        targetDescription: desc,
      });
    } else if (tag === "input") {
      const inputEl = target as HTMLInputElement;
      const type = (inputEl.type || "").toLowerCase();

      if (type === "checkbox" || type === "radio") {
        const isChecked = inputEl.checked;
        emitStep({
          action: isChecked ? "check" : "uncheck",
          name: `${isChecked ? "Check" : "Uncheck"} ${desc}`,
          primarySelector: primary,
          fallbackSelectors: fallbacks,
          value: String(isChecked),
          timestamp: Date.now(),
          targetDescription: desc,
        });
      } else if (type === "file") {
        const files = Array.from(inputEl.files || []).map((f) => f.name).join(", ");
        emitStep({
          action: "upload",
          name: `Upload files [${files}] into ${desc}`,
          primarySelector: primary,
          fallbackSelectors: fallbacks,
          value: files,
          timestamp: Date.now(),
          targetDescription: desc,
        });
      }
    }
  },
  true
);

// Key presses: Enter, Tab, Escape
window.addEventListener(
  "keydown",
  (e: KeyboardEvent) => {
    if (!isRecording) return;
    if (["Enter", "Tab", "Escape"].includes(e.key)) {
      clearTimeout(inputDebounceTimer);
      flushPendingInput();

      const target = (e.target as HTMLElement) || document.body;
      const { primary, fallbacks } = generateSelectors(target);
      const desc = getElementDescription(target);

      emitStep({
        action: "keypress",
        name: `Press ${e.key} on ${desc}`,
        primarySelector: primary,
        fallbackSelectors: fallbacks,
        value: e.key,
        timestamp: Date.now(),
        targetDescription: desc,
      });
    }
  },
  true
);

// -------------------------------------------------------------
// RIGHT-CLICK ASSERTION MENU
// -------------------------------------------------------------

window.addEventListener(
  "contextmenu",
  (e: MouseEvent) => {
    if (!isRecording) return;
    e.preventDefault();

    if (activeContextMenu) {
      activeContextMenu.remove();
      activeContextMenu = null;
    }

    const target = (e.target as HTMLElement);
    if (!target) return;

    const { primary, fallbacks } = generateSelectors(target);
    const desc = getElementDescription(target);
    const targetText = (target.innerText || target.textContent || "").trim().slice(0, 30);
    const currentUrl = window.location.href;

    // Create sleek dark context menu
    const menu = document.createElement("div");
    activeContextMenu = menu;
    menu.id = "__qa_assertion_menu";
    Object.assign(menu.style, {
      position: "fixed",
      left: `${Math.min(e.clientX, window.innerWidth - 240)}px`,
      top: `${Math.min(e.clientY, window.innerHeight - 200)}px`,
      zIndex: "2147483647",
      background: "#18181b",
      border: "1px solid #3f3f46",
      borderRadius: "8px",
      boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.5)",
      padding: "6px",
      fontFamily: "system-ui, -apple-system, sans-serif",
      fontSize: "13px",
      color: "#f4f4f5",
      width: "230px",
    });

    const header = document.createElement("div");
    header.innerText = `Add Assertion: ${desc.slice(0, 20)}`;
    Object.assign(header.style, {
      padding: "4px 8px",
      fontWeight: "600",
      fontSize: "11px",
      textTransform: "uppercase",
      color: "#a1a1aa",
      borderBottom: "1px solid #27272a",
      marginBottom: "4px",
    });
    menu.appendChild(header);

    const items = [
      {
        icon: "👁️",
        label: "Assert visible",
        action: () => {
          emitStep({
            action: "assert_visible",
            name: `Assert visible: ${desc}`,
            primarySelector: primary,
            fallbackSelectors: fallbacks,
            timestamp: Date.now(),
            targetDescription: desc,
          });
        },
      },
      {
        icon: "📝",
        label: `Assert text equals "${targetText || '...'}"`,
        action: () => {
          emitStep({
            action: "assert_text_equals",
            name: `Assert text: "${targetText}" on ${desc}`,
            primarySelector: primary,
            fallbackSelectors: fallbacks,
            value: targetText,
            timestamp: Date.now(),
            targetDescription: desc,
          });
        },
      },
      {
        icon: "🔗",
        label: "Assert URL contains current path",
        action: () => {
          const pathSnippet = window.location.pathname;
          emitStep({
            action: "assert_url_contains",
            name: `Assert URL contains "${pathSnippet}"`,
            value: pathSnippet,
            url: currentUrl,
            timestamp: Date.now(),
          });
        },
      },
      {
        icon: "🔢",
        label: "Assert element count >= 1",
        action: () => {
          emitStep({
            action: "assert_element_count",
            name: `Assert count for ${desc}`,
            primarySelector: primary,
            fallbackSelectors: fallbacks,
            value: "1",
            timestamp: Date.now(),
            targetDescription: desc,
          });
        },
      },
    ];

    items.forEach((item) => {
      const btn = document.createElement("button");
      btn.innerHTML = `<span style="margin-right:8px">${item.icon}</span>${item.label}`;
      Object.assign(btn.style, {
        display: "block",
        width: "100%",
        textAlign: "left",
        background: "transparent",
        border: "none",
        color: "#e4e4e7",
        padding: "6px 8px",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "12px",
        transition: "background 0.15s",
      });
      btn.onmouseenter = () => {
        btn.style.background = "#27272a";
      };
      btn.onmouseleave = () => {
        btn.style.background = "transparent";
      };
      btn.onclick = () => {
        item.action();
        menu.remove();
        activeContextMenu = null;
      };
      menu.appendChild(btn);
    });

    document.body.appendChild(menu);

    // Close on click outside
    const closeListener = (evt: MouseEvent) => {
      if (!menu.contains(evt.target as Node)) {
        menu.remove();
        activeContextMenu = null;
        window.removeEventListener("click", closeListener, true);
      }
    };
    window.addEventListener("click", closeListener, true);
  },
  true
);

console.log("🎯 QA Recorder content script injected successfully");
